### ISSUE TITLE
Homebrew support?

### ISSUE THREAD

**Issue by sean-** [moderato-app/approf#1]
`brew install approf`?

**Comment by clement2026** [comment]
Thanks for bringing this up! I love `brew install` as well.

Based on [Homebrew's guidelines](https://docs.brew.sh/Acceptable-Casks#rejected-casks), this repo needs a few more stars to be considered for Homebrew casks. Once it meets the criteria, `brew install` will be supported.

Let’s keep this issue open so we can track the progress.

**Comment by clement2026** [comment]
The PR at https://github.com/Homebrew/homebrew-cask/pull/181782 failed some tests. Let's retry on September 6th.

```bash
Run brew audit --cask --online --new --signing 'approf'
==> Downloading https://github.com/moderato-app/approf/releases/download/v14.1.0/approf.app.zip
Already downloaded: /Users/runner/Library/Caches/Homebrew/downloads/c165e408d1c634ef9b3a6d41048041f25e2c770d9768a6d5b470dda60fd6ebf6--approf.app.zip
==> Downloading and extracting artifacts
==> Downloading https://github.com/moderato-app/approf/releases/download/v14.1.0/approf.app.zip
Already downloaded: /Users/runner/Library/Caches/Homebrew/downloads/c165e408d1c634ef9b3a6d41048041f25e2c770d9768a6d5b470dda60fd6ebf6--approf.app.zip
audit for approf: failed
 - GitHub repository too new (<30 days old)
approf
  * line 5, col 2: GitHub repository too new (<30 days old)
Error: 1 problem in 1 cask detected.
Error: 1 problem in 1 cask detected.
Error: GitHub repository too new (<30 days old)
Error: Process completed with exit code 1.
```

**Comment by lukasmalkmus** [comment]
Just wanna point out that the instructions on https://github.com/moderato-app/approf?tab=readme-ov-file#install are not working.

**Comment by clement2026** [comment]
@lukasmalkmus Thanks for the feedback!

Could you share more details to help me understand what happened? Specifically what error did the brew command return?

**Comment by Akagi201** [comment]
https://github.com/moderato-app/homebrew-brew repo does not exist

**Comment by clement2026** [comment]
> https://github.com/moderato-app/homebrew-brew repo does not exist

@Akagi201 Thanks for the heads-up! I didn’t realize the repo was private.

I just made it public. Can you try again now?

**Comment by clement2026** [comment]
This issue is resolved by https://github.com/Homebrew/homebrew-cask/pull/181782.

Before installing `approf` from the official Homebrew, make sure you uninstall the old version by running:
```
brew uninstall moderato-app/homebrew-brew/approf
brew untap moderato-app/homebrew-brew
```
Once that's done, you can install the new version with:
```
brew info approf
```

Thanks, everyone, for your help!

Closing this.
